spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/chinanov?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 3063115730@qq.com
    password: vlzcjtaokeerddha
    properties:
      from: 3063115730@qq.com
    port: 587
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/*.xml
